= C++ example project manually scanned on SonarQube


It is very easy to manually analyze a C, C++ and Objective-C project with SonarQube:

. Create a `sonar-project.properties` file to store your configuration
.. Add a projectKey of your project
.. Add a Build Wrapper output directory
.. https://docs.sonarqube.org/latest/user-guide/user-token/[Generate a unique token] and set it as "sonar.login" (`SONARQUBE_TOKEN` in this example project)
.. Set `sonar.host.url` to your SonarQube server URL
. Download and unzip the Build Wrapper for macOS from {SonarQube URL}/static/cpp/build-wrapper-macosx-x86.zip
. Add the Build Wrapper to your `$PATH`
. Download and unzip the https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[SonarScanner] for macOS
. Add the bin directory of the SonarScanner to your `$PATH`
. Wrap your clean build command with the Build Wrapper. E.g.: `build-wrapper-macosx-x86 --out-dir bw-output xcodebuild clean build`
. Run `sonar-scanner` specifying `-Dsonar.cfamily.build-wrapper-output=bw-output` (with `bw-output` being the same directory as the one passed to Build Wrapper as `--out-dir`)

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:build-analyze.sh[build-analyze.sh] (a script that downloads the `sonar-scanner` and the Build Wrapper before compiling and analyzing the project) to see it in practice. Please be aware that the SonarQube server URLs and the `sonar.login` are not completed in these examples.

= Documentation
- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C, C++ and Objective-C plugin and its Build Wrapper]
- https://docs.sonarqube.org/latest/analyzing-source-code/languages/c-family/#analysis-cache[Configuring C, C++ and Objective-C analysis cache]
- https://docs.sonarqube.org/latest/analyzing-source-code/languages/c-family/#parallel-code-scan[Configuring multithreaded execution]

= macOS\XCodeBuild

A build of the https://github.com/sonarsource-cfamily-examples/code[code repository] on a macOS using XCode build system.

To build the code run from the repository root directory:
----
xcodebuild
----

= Code Description

An example of a flawed C++ code. The https://github.com/sonarsource-cfamily-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, macOS, and Windows.

The https://github.com/sonarsource-cfamily-examples/code[code repository] is forked into other repositories in https://github.com/sonarsource-cfamily-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sonarsource-cfamily-examples?q=linux[Linux]
* https://github.com/sonarsource-cfamily-examples?q=macos[macOS]
* https://github.com/sonarsource-cfamily-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sonarsource-cfamily-examples?q=cmake[CMake]
* https://github.com/sonarsource-cfamily-examples?q=autotools[GNU Autotools]
* https://github.com/sonarsource-cfamily-examples?q=xcode[Xcode]
* https://github.com/sonarsource-cfamily-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sonarsource-cfamily-examples?q=azure[Azure DevOps]
* https://github.com/sonarsource-cfamily-examples?q=gh-actions[GitHub Actions]
* https://github.com/sonarsource-cfamily-examples?q=travis[Travis]
* https://github.com/sonarsource-cfamily-examples?q=jenkins[Jenkins]
* https://github.com/sonarsource-cfamily-examples?q=gitlab[GitLab CI]
* https://github.com/sonarsource-cfamily-examples?q=bitbucket[BitBucket Pipelines]
* Additionally, https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=otherci[generic examples] demonstrate integration with other CIs and https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=manual[manual-configuration examples] should help you if you are running locally.

Configured for analysis on:

* https://github.com/sonarsource-cfamily-examples?q=-sq[SonarQube]
* https://github.com/sonarsource-cfamily-examples?q=-sc[SonarCloud]

You can find also a few examples demonstrating:

* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=compdb[The use of Compilation Database (compile_commands.json)]
* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=topic%3Acoverage[Test coverage]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sonarsource-cfamily-examples[this GitHub organization] and the relations between its different repositories.
