= C++ example project manually scanned on SonarQube

It is very easy to manually analyze a C/C++/Objective-C project with SonarQube:

. Create a `sonar-project.properties` file to store your configuration
.. Add a projectKey of your project
.. Add a Build Wrapper output directory
.. https://docs.sonarqube.org/latest/user-guide/user-token/[Generate a unique token] and set it as "sonar.login"
.. Set `sonar.host.url` to your SonarQube server URL
. Download and unzip the Build Wrapper for MacOS from {SonarQube URL}/static/cpp/build-wrapper-macosx-x86.zip
. Add the Build Wrapper to your `%PATH%`
. Download and unzip the https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[SonarScanner] for MacOS
. Add the bin directory of the SonarScanner to your `%PATH%`
. Wrap your clean build command with the Build Wrapper. E.g.: `build-wrapper-macosx-x86 --out-dir bw-output xcodebuild clean build` (with `bw-output` being the same directory that the one set in `sonar-project.properties`)
. Run `sonar-scanner`

You can take a look at the link:sonar-project.properties[sonar-project.properties] to see it in practice. Please be aware that the SonarQube server URL and the `sonar.login` are not completed in this example.

= Documentation
- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C/C++/Objective-C plugin and its Build Wrapper]

= MacOS\XCodeBuild

A build of the https://github.com/sc-sq-c-family-examples/code[code repository] on a MacOS using XCode build system.

To build the code run from the repository root directory:
----
xcodebuild
----

= Code Description

An example of a flawed C++ code. The https://github.com/sc-sq-c-family-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, MacOS, and Windows.

The https://github.com/sc-sq-c-family-examples/code[code repository] is forked into other repositories in https://github.com/sc-sq-c-family-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sc-sq-c-family-examples?q=linux[Linux]
* https://github.com/sc-sq-c-family-examples?q=macos[MacOS]
* https://github.com/sc-sq-c-family-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sc-sq-c-family-examples?q=cmake[CMake]
* https://github.com/sc-sq-c-family-examples?q=autotools[GNU Autotools]
* https://github.com/sc-sq-c-family-examples?q=xcode[Xcode]
* https://github.com/sc-sq-c-family-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sc-sq-c-family-examples?q=azure[Azure DevOps]
* https://github.com/sc-sq-c-family-examples?q=gh-actions[GitHub Actions]
* https://github.com/sc-sq-c-family-examples?q=travis[Travis]
* https://github.com/sc-sq-c-family-examples?q=jenkins[Jenkins]
* https://github.com/sc-sq-c-family-examples?q=gitlab[GitLab CI]
* https://github.com/sc-sq-c-family-examples?q=bitbucket[BitBucket Pipelines]

Configured for analysis on:

* https://github.com/sc-sq-c-family-examples?q=-sq[SonarQube]
* https://github.com/sc-sq-c-family-examples?q=-sc[SonarCloud]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sc-sq-c-family-examples[this GitHub organization] and the relations between its different repositories.
